# Generated by Django 3.2.9 on 2021-12-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopart',
            name='price',
            field=models.BigIntegerField(default=1100),
            preserve_default=False,
        ),
    ]
