# Generated by Django 3.2.9 on 2021-12-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_autopart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carApp.car'),
            preserve_default=False,
        ),
    ]
