# Generated by Django 3.2.9 on 2021-12-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0003_booking_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partorder',
            old_name='order',
            new_name='order_id',
        ),
    ]
