# Generated by Django 3.2.9 on 2021-12-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0004_rename_order_partorder_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partorder',
            old_name='order_id',
            new_name='order',
        ),
    ]
